name: Integration testing (multiple dbt versions)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DBT_PROJECT_DIR: integration_tests
  DBT_PROFILES_DIR: integration_tests
  BIGQUERY_PROJECT: dbt-date
  BIGQUERY_KEYFILE_JSON: ${{ secrets.BIGQUERY_KEYFILE_JSON }}
  BIGQUERY_SCHEMA: "integration_tests_bigquery_${{ github.run_number }}"
  CLICKHOUSE_HOST: localhost
  CLICKHOUSE_PORT: "8123"
  CLICKHOUSE_SCHEMA: dbt_date
  CLICKHOUSE_USER: default
  DBT_ENV_SECRET_DATABRICKS_TOKEN: "${{ secrets.DBT_ENV_SECRET_DATABRICKS_TOKEN }}"
  DATABRICKS_HTTP_PATH: "${{ vars.DATABRICKS_HTTP_PATH }}"
  DATABRICKS_HOST: "${{ vars.DATABRICKS_HOST }}"
  DATABRICKS_SCHEMA: "dbt_date_${{ github.run_number }}"
  DBT_ENV_SECRET_POSTGRES_PASS: dbt
  POSTGRES_DATABASE: metastore
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  POSTGRES_SCHEMA: dbt_date
  POSTGRES_USER: dbt
  SPARK_HOST: localhost
  SPARK_METHOD: thrift
  SPARK_PORT: 10000
  SPARK_SCHEMA: dbt_date
  SPARK_USER: dbt
  DBT_ENV_SECRET_TRINO_PASS: dbt
  TRINO_CATALOG: dbt
  TRINO_HOST: localhost
  TRINO_METHOD: none
  TRINO_PORT: "8080"
  TRINO_SCHEMA: dbt
  TRINO_TIMEZONE: UTC
  TRINO_USER: dbt
jobs:
  integration_tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        adapter:
          - bigquery
          - clickhouse
          - databricks
          - duckdb
          - postgres
          - spark
          - trino
        dbt-version:
          - "1.10"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dbt-${{ matrix.adapter }}~=${{ matrix.dbt-version }} (including Spark extra)
        if: ${{ matrix.adapter == 'spark' }}
        run: pip install "dbt-${{ matrix.adapter }}[PyHive]~=${{ matrix.dbt-version }}.0" "dbt-core~=${{ matrix.dbt-version }}.0" tox

      - name: Install dbt-${{ matrix.adapter }}~=${{ matrix.dbt-version }}
        if: ${{ matrix.adapter != 'spark' && !(matrix.adapter == 'bigquery' && matrix.dbt-version == '1.6') }}
        run: pip install "dbt-${{ matrix.adapter }}~=${{ matrix.dbt-version }}.0" "dbt-core~=${{ matrix.dbt-version }}.0" tox

      - name: Install testing dependencies (non-python)
        if: ${{ matrix.adapter == 'clickhouse' || matrix.adapter == 'postgres' || matrix.adapter == 'spark' || matrix.adapter == 'trino' }}
        run: |
          docker compose -f ./integration_tests/docker-compose.yml up -d dbt-${{ matrix.adapter }}
          sleep 30

      - name: Run integration tests (${{ matrix.adapter }})
        run: |
          export DBT_SUFFIX=_$(date +%6N)
          tox -e dbt_integration_${{ matrix.adapter }}

  integration_tests_fusion:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        adapter:
          - bigquery
          - databricks

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      # Having a DuckDB adapter in profiles.yml is unsupported by Fusion (even if unused)
      - name: Update profiles.yml
        run: |
          yq -i eval 'del .integration_tests.outputs.duckdb' ./integration_tests/profiles.yml
          yq -i eval '.integration_tests.target = "bigquery"' ./integration_tests/profiles.yml

      # Fusion for BigQuery requires a different auth method
      - name: Save BigQuery key file as a file
        if: ${{ matrix.adapter == 'bigquery' }}
        run: |
          echo -n "${{ secrets.BIGQUERY_KEYFILE_JSON_BASE64 }}" | base64 --decode >> ./integration_tests/service-key-file.json

      - name: Install tox
        run: pip install tox

      - name: Install dbt Fusion
        run: |
          curl -fsSL https://public.cdn.getdbt.com/fs/install/install.sh | sh -s -- --update
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify dbt installation
        run: dbt --version

      - name: Run fusion integration tests (${{ matrix.adapter }})
        env:
          BIGQUERY_KEYFILE_JSON: ${{ secrets.BIGQUERY_KEYFILE_JSON }}
          BIGQUERY_PROJECT: ${{ env.BIGQUERY_PROJECT }}
          BIGQUERY_SCHEMA: ${{ env.BIGQUERY_SCHEMA }}
          DBT_ENV_SECRET_DATABRICKS_TOKEN: ${{ secrets.DBT_ENV_SECRET_DATABRICKS_TOKEN }}
          DATABRICKS_HTTP_PATH: ${{ vars.DATABRICKS_HTTP_PATH }}
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_SCHEMA: ${{ env.DATABRICKS_SCHEMA }}
        run: |
          export DBT_SUFFIX=_$(date +%6N)
          tox -e fusion_integration_${{ matrix.adapter }}
